import { Employee } from '@teq-task/shared';

export const EMPLOYEES: Employee[] = [
  {
    id: 'vvv1323',
    name: 'John Doe',
    department: 'Engineering',
    status: 'ACTIVE',
    email: 'john.doe@company.com',
    equipments: [
      { id: 'aaa123456', name: 'MacBook Air' },
      { id: 'aaa123457', name: 'Magic Mouse' },
    ],
  },
  {
    id: 'vvv1324',
    name: 'Jane Smith',
    department: 'Marketing',
    status: 'ACTIVE',
    email: 'jane.smith@company.com',
    equipments: [
      { id: 'aaa123458', name: 'MacBook Pro' },
      { id: 'aaa123459', name: 'Apple Keyboard' },
    ],
  },
  {
    id: 'vvv1325',
    name: 'James Brown',
    department: 'Sales',
    status: 'ACTIVE',
    email: 'james.brown@company.com',
    equipments: [
      { id: 'aaa123460', name: 'MacBook Air' },
      { id: 'aaa123461', name: 'Magic Mouse' },
    ],
  },
  {
    id: 'vvv1326',
    name: 'Emily White',
    department: 'Engineering',
    status: 'INACTIVE',
    email: 'emily.white@company.com',
    equipments: [
      { id: 'aaa123462', name: 'MacBook Air' },
      { id: 'aaa123463', name: 'Apple Magic Trackpad' },
    ],
  },
  {
    id: 'vvv1327',
    name: 'Michael Harris',
    department: 'Human Resources',
    status: 'ACTIVE',
    email: 'michael.harris@company.com',
    equipments: [
      { id: 'aaa123464', name: 'MacBook Pro' },
      { id: 'aaa123465', name: 'Apple Keyboard' },
    ],
  },
  {
    id: 'vvv1328',
    name: 'Sarah Miller',
    department: 'Engineering',
    status: 'ACTIVE',
    email: 'sarah.miller@company.com',
    equipments: [
      { id: 'aaa123466', name: 'MacBook Air' },
      { id: 'aaa123467', name: 'Magic Mouse' },
    ],
  },
  {
    id: 'vvv1329',
    name: 'David Clark',
    department: 'Sales',
    status: 'ACTIVE',
    email: 'david.clark@company.com',
    equipments: [
      { id: 'aaa123468', name: 'MacBook Pro' },
      { id: 'aaa123469', name: 'Apple Keyboard' },
    ],
  },
  {
    id: 'vvv1330',
    name: 'Laura Lewis',
    department: 'Marketing',
    status: 'INACTIVE',
    email: 'laura.lewis@company.com',
    equipments: [
      { id: 'aaa123470', name: 'MacBook Air' },
      { id: 'aaa123471', name: 'Apple Magic Trackpad' },
    ],
  },
  {
    id: 'vvv1331',
    name: 'Thomas Walker',
    department: 'Engineering',
    status: 'ACTIVE',
    email: 'thomas.walker@company.com',
    equipments: [
      { id: 'aaa123472', name: 'MacBook Air' },
      { id: 'aaa123473', name: 'Magic Mouse' },
    ],
  },
  {
    id: 'vvv1332',
    name: 'Elizabeth King',
    department: 'Human Resources',
    status: 'ACTIVE',
    email: 'elizabeth.king@company.com',
    equipments: [
      { id: 'aaa123474', name: 'MacBook Pro' },
      { id: 'aaa123475', name: 'Apple Keyboard' },
    ],
  },
  {
    id: 'vvv1333',
    name: 'Brian Scott',
    department: 'Sales',
    status: 'INACTIVE',
    email: 'brian.scott@company.com',
    equipments: [
      { id: 'aaa123476', name: 'MacBook Air' },
      { id: 'aaa123477', name: 'Magic Mouse' },
    ],
  },
  {
    id: 'vvv1334',
    name: 'Grace Johnson',
    department: 'Marketing',
    status: 'ACTIVE',
    email: 'grace.johnson@company.com',
    equipments: [
      { id: 'aaa123478', name: 'MacBook Pro' },
      { id: 'aaa123479', name: 'Apple Keyboard' },
    ],
  },
  {
    id: 'vvv1335',
    name: 'Oscar Wilson',
    department: 'Engineering',
    status: 'ACTIVE',
    email: 'oscar.wilson@company.com',
    equipments: [
      { id: 'aaa123480', name: 'MacBook Air' },
      { id: 'aaa123481', name: 'Magic Mouse' },
    ],
  },
  {
    id: 'vvv1336',
    name: 'Lily Davis',
    department: 'Sales',
    status: 'INACTIVE',
    email: 'lily.davis@company.com',
    equipments: [
      { id: 'aaa123482', name: 'MacBook Pro' },
      { id: 'aaa123483', name: 'Apple Keyboard' },
    ],
  },
  {
    id: 'vvv1337',
    name: 'Henry Taylor',
    department: 'Marketing',
    status: 'ACTIVE',
    email: 'henry.taylor@company.com',
    equipments: [
      { id: 'aaa123484', name: 'MacBook Air' },
      { id: 'aaa123485', name: 'Magic Mouse' },
    ],
  },
  {
    id: 'vvv1338',
    name: 'Natalie Anderson',
    department: 'Human Resources',
    status: 'ACTIVE',
    email: 'natalie.anderson@company.com',
    equipments: [
      { id: 'aaa123486', name: 'MacBook Pro' },
      { id: 'aaa123487', name: 'Apple Keyboard' },
    ],
  },
  {
    id: 'vvv1339',
    name: 'Adam Thomas',
    department: 'Sales',
    status: 'INACTIVE',
    email: 'adam.thomas@company.com',
    equipments: [
      { id: 'aaa123488', name: 'MacBook Air' },
      { id: 'aaa123489', name: 'Magic Mouse' },
    ],
  },
  {
    id: 'vvv1340',
    name: 'Sophia Martinez',
    department: 'Engineering',
    status: 'ACTIVE',
    email: 'sophia.martinez@company.com',
    equipments: [
      { id: 'aaa123490', name: 'MacBook Pro' },
      { id: 'aaa123491', name: 'Apple Keyboard' },
    ],
  },
  {
    id: 'vvv1341',
    name: 'Lucas Garcia',
    department: 'Marketing',
    status: 'ACTIVE',
    email: 'lucas.garcia@company.com',
    equipments: [
      { id: 'aaa123492', name: 'MacBook Air' },
      { id: 'aaa123493', name: 'Magic Mouse' },
    ],
  },
  {
    id: 'vvv1342',
    name: 'Mia Rodriguez',
    department: 'Sales',
    status: 'ACTIVE',
    email: 'mia.rodriguez@company.com',
    equipments: [
      { id: 'aaa123494', name: 'MacBook Pro' },
      { id: 'aaa123495', name: 'Apple Keyboard' },
    ],
  },
  {
    id: 'vvv1343',
    name: 'Daniel Lee',
    department: 'Engineering',
    status: 'INACTIVE',
    email: 'daniel.lee@company.com',
    equipments: [
      { id: 'aaa123496', name: 'MacBook Air' },
      { id: 'aaa123497', name: 'Magic Mouse' },
    ],
  },
  {
    id: 'vvv1344',
    name: 'Alice Wilson',
    department: 'Marketing',
    status: 'ACTIVE',
    email: 'alice.wilson@company.com',
    equipments: [
      { id: 'aaa123498', name: 'MacBook Pro' },
      { id: 'aaa123499', name: 'Apple Keyboard' },
    ],
  },
  {
    id: 'vvv1345',
    name: 'Ethan Martin',
    department: 'Sales',
    status: 'INACTIVE',
    email: 'ethan.martin@company.com',
    equipments: [
      { id: 'aaa123500', name: 'MacBook Air' },
      { id: 'aaa123501', name: 'Magic Mouse' },
    ],
  },
  {
    id: 'vvv1346',
    name: 'Chloe Harris',
    department: 'Human Resources',
    status: 'ACTIVE',
    email: 'chloe.harris@company.com',
    equipments: [
      { id: 'aaa123502', name: 'MacBook Pro' },
      { id: 'aaa123503', name: 'Apple Keyboard' },
    ],
  },
  {
    id: 'vvv1347',
    name: 'William King',
    department: 'Marketing',
    status: 'ACTIVE',
    email: 'william.king@company.com',
    equipments: [
      { id: 'aaa123504', name: 'MacBook Air' },
      { id: 'aaa123505', name: 'Magic Mouse' },
    ],
  },
  {
    id: 'vvv1348',
    name: 'Zoe Clark',
    department: 'Engineering',
    status: 'ACTIVE',
    email: 'zoe.clark@company.com',
    equipments: [
      { id: 'aaa123506', name: 'MacBook Pro' },
      { id: 'aaa123507', name: 'Apple Keyboard' },
    ],
  },
  {
    id: 'vvv1349',
    name: 'Michael Lee',
    department: 'Human Resources',
    status: 'INACTIVE',
    email: 'michael.lee@company.com',
    equipments: [
      { id: 'aaa123508', name: 'MacBook Air' },
      { id: 'aaa123509', name: 'Magic Mouse' },
    ],
  },
  {
    id: 'vvv1350',
    name: 'Victoria Rodriguez',
    department: 'Sales',
    status: 'ACTIVE',
    email: 'victoria.rodriguez@company.com',
    equipments: [
      { id: 'aaa123510', name: 'MacBook Pro' },
      { id: 'aaa123511', name: 'Apple Keyboard' },
    ],
  },
  {
    id: 'vvv1351',
    name: 'Jacob Scott',
    department: 'Marketing',
    status: 'INACTIVE',
    email: 'jacob.scott@company.com',
    equipments: [
      { id: 'aaa123512', name: 'MacBook Air' },
      { id: 'aaa123513', name: 'Magic Mouse' },
    ],
  },
  {
    id: 'vvv1352',
    name: 'Sophia Taylor',
    department: 'Sales',
    status: 'ACTIVE',
    email: 'sophia.taylor@company.com',
    equipments: [
      { id: 'aaa123514', name: 'MacBook Pro' },
      { id: 'aaa123515', name: 'Apple Keyboard' },
    ],
  },
  {
    id: 'vvv1353',
    name: 'Ryan Williams',
    department: 'Engineering',
    status: 'ACTIVE',
    email: 'ryan.williams@company.com',
    equipments: [
      { id: 'aaa123516', name: 'MacBook Air' },
      { id: 'aaa123517', name: 'Magic Mouse' },
    ],
  },
  {
    id: 'vvv1354',
    name: 'Charlotte Evans',
    department: 'Marketing',
    status: 'ACTIVE',
    email: 'charlotte.evans@company.com',
    equipments: [
      { id: 'aaa123518', name: 'MacBook Pro' },
      { id: 'aaa123519', name: 'Apple Keyboard' },
    ],
  },
  {
    id: 'vvv1355',
    name: 'Aiden Garcia',
    department: 'Sales',
    status: 'INACTIVE',
    email: 'aiden.garcia@company.com',
    equipments: [
      { id: 'aaa123520', name: 'MacBook Air' },
      { id: 'aaa123521', name: 'Magic Mouse' },
    ],
  },
];
